services:
  projectzomboid:
    image: indifferentbroccoli/projectzomboid-server-docker
    restart: unless-stopped
    container_name: projectzomboid
    stop_grace_period: 30s
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
      - 27015:27015/tcp
    environment:
      - GENERATE_SETTINGS=false
      - PUID=1000
      - PGID=1000
      - GENERATE_SETTINGS=true
      - SERVER_NAME=PimmelServer
      - SERVER_PASSWORD=Pimmel
      - ADMIN_PASSWORD=Foobar1!
      - STEAM_VAC=true
      - SERVER_WELCOME_MESSAGE=Penis
      - MODS=2875848298;1299328280;2553809727;2901962885
      - SERVER_BRANCH=42.13.1
      - MEMORY_XMX_GB=8
    volumes:
      - ./server-files:/project-zomboid
      - ./server-data:/project-zomboid-config
